### DISCUSSION TITLE
Azure Pipelines & WASM

### DISCUSSION THREAD

**Discussion by Wandtket** [unoplatform/uno#10240] [Q&A]
I was originally using Azure App Service to publish my Uno Web Assembly app, then I needed to configure URL routing and it appears I can't do that unless I use an Azure Static Web App [found here](https://platform.uno/docs/articles/guides/azure-static-webapps.html): 

My issue was I was attempting to use my existing Azure Devops and use pipelines, however, for the life of me I can't get it to build correctly. My .yml file that was auto generated is this:

```
name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - main
trigger:
  branches:
    include:
      - main

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-green-field-0d2fab910-variable-group
  steps:
  - checkout: self
    submodules: true

  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_FIELD_0D2FAB910)
      

###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "" # Built app content directory - optional
###### End of Repository/Build Configurations ######
```

This doesn't build but when I follow the documentation it still doesn't build properly

```
name: Azure Static Web Apps CI/CD
pr:
  branches:
    include:
      - main
trigger:
  branches:
    include:
      - main

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-green-field-0d2fab910-variable-group
  steps:
  - checkout: self
    submodules: true
    - name: Setup dotnet
uses: actions/setup-dotnet@v1.7.2
with:
    dotnet-version: '5.0.103'

- run: |
    cd src/MyApp.Wasm
    dotnet build -c Release

  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_FIELD_0D2FAB910)
      


###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
# For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      app_location: "" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "" # Built app content directory - optional
###### End of Repository/Build Configurations ######
```

Please note I am replacing MyApp.Wasm with the name of the project.
