### DISCUSSION TITLE
[WASM] Injected Hyperlink Css Style

### DISCUSSION THREAD

**Discussion by michael-hawker** [unoplatform/uno#10396] [Q&A]
_Originally [asked on Discord](https://discord.com/channels/372137812037730304/550416151172087808/1040331976885944352)_

I'm creating a WASM interop component which injects some HTML into the DOM for its content. The HTML content I'm giving to `SetHtmlContent` content contains a link `<a>`. 

How do I style the link to not be the default ugly BLUE color for hyperlinks and feel more like a native `Hyperlink` in fluent style?

Is there some magic Uno CSS class I could apply to the root tag of my injected HTML with `SetCssClass`?

**Comment by michael-hawker** [comment]
For now, I just modified the `Fonts.css` file in the project head and used `SetCssClass` to add a theme-aware style selector:

```css
/* Hyperlink Theme Aware Link Color https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme */
@media (prefers-color-scheme: dark)
{
  .fluent-hyperlink-style a {
     color: #FFFFFF;
  }
}

@media (prefers-color-scheme: light) {
  .fluent-hyperlink-style a {
    color: #000000;
  }
}
```

This is fine for now as we control the stack, but would be handy to know an easier way to add this style chunk as part of the control itself. Reminds me of shadow doms for web components in a way...

One suggestion was to just add a `<style>` tag within the html I'm injecting, which I suppose could work as well, at least the new raw string literals in C# will help with that sort of thing as well to inline.

I feel like that would clutter the DOM a bit though with multiple instances of the component, would be kind of handy to have something that's shared/cached between instances of the control. i.e. define some control-local CSS snippet that can define whatever is needed.
