### DISCUSSION TITLE
How do we get dSYM file for net6.0-ios apps?

### DISCUSSION THREAD

**Discussion by jeanplevesque** [unoplatform/uno#10628] [Q&A] [answered]
We're trying to build a release pipeline for an iOS app (using net6-ios and WinUI APIs).
The build itself works and we get an .ipa but we don't get any dSYM.

Here's our binlog.
[build-net6.0-ios.binlog.zip](https://github.com/unoplatform/uno/files/10142254/build-net6.0-ios.binlog.zip)

We looked at your Gallery app for reference and found that it also doesn't generate any dSYM 🤔.

It's really important for us to get a dSYM in order to have good crash reporting.

**Comment by spouliot** [comment, marked as answer]
Try adding `<NoDSymUtil>false</NoDSymUtil>` inside your `.csproj` file and the Rebuild the project.

Note that it won't be copied to the same directory as the `.ipa` file. That's a [known issue](https://github.com/xamarin/xamarin-macios/issues/15384) in the iOS SDK.

**Reply by Soap-141** [reply]
So if I do this, it should be able to find it?
``` yml
- task: CopyFiles@2
  displayName: 'Copy DSYM'
  inputs:
    Contents: '**/*.dsym/**'
    flattenFolders : true
    SourceFolder: '${{ parameters.pathToSrc }}/app/${{ parameters.solutionName }}.Mobile/bin/Release/net6.0-ios'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
```

**Reply by Soap-141** [reply]
Also I tried with `<NoDSymUtil>false</NoDSymUtil>` and still nothing. Copy file can't find it.

**Reply by spouliot** [reply]
Not sure about the yaml... and if `Contents` is case sensitive. You better use `*.dSYM' to avoid problems.

As for the `<NoDSymUtil>false</NoDSymUtil>` make sure to add it inside a property group that is executed for `net6.0-ios` and for your build configuration.

**Reply by Soap-141** [reply]
It worked! My copy file contents property was wrong and I also added `NoDSymUtil` to be safe.
``` yml
- task: CopyFiles@2
  displayName: 'Copy DSYM'
  inputs:
    Contents: '**/*.dSYM/**'
    flattenFolders : true
    SourceFolder: '${{ parameters.pathToSrc }}/app/${{ parameters.solutionName }}.Mobile/bin/Release/net6.0-ios'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/${{ parameters.solutionName }}.Mobile.dSYM'
```
Thanks for the help.
