### DISCUSSION TITLE
Building a simple Uno Platform application on AWS

### DISCUSSION THREAD

**Discussion by jeromelaban** [unoplatform/uno#10815] [Q&A]
[_From Discord_:](https://discord.com/channels/372137812037730304/550416151172087808/1055695247620976690)

I'm building a simple Uno Platform application on AWS. I have everything setup and provisioned locally using dotnet SDK 6.0 on VS Code. But the project builds on Amplify fails at frontend. Here's the error message:

```
2022-12-23T03:32:59.392Z [INFO]: Build FAILED.
/usr/share/dotnet/sdk/3.1.416/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/codebuild/output/src041914325/src/UnoWasmAWS/MyApp.Wasm/MyApp.Wasm.csproj]
0 Warning(s)
1 Error(s)
```

Any ideas :/

**Comment by jeromelaban** [comment]
This looks like you're not using the right .NET SDK for some reason (3.1.416 is being used).

How are you installing the .NET SDK ?

**Reply by dcoartist** [reply]
I have dotnet 6.0.4 installed on Linux Mint 20.3. Would probably do an upgrade but the idea is to have a sample Uno Wasm application up and running on AWS. I can comfortably build and deploy from the Skia.Gtk directory but I figured building for Wasm would require WinUI library which is not available on Linux. Here's the link to the repo: https://github.com/davidconoh/UnoWasmAWS.git/

**Reply by jeromelaban** [reply]
Thanks. For some reason, it seems that the build is still using .NET 3.1 instead. You may want to add `./dotnet6` to your `PATH` so it gets used first, or use `source ./dotnet-install.sh`. See [this documentation on how to install .NET](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#manual-install) for your environment.

**Comment by dcoartist** [comment]
@jeromelaban Here's an update: Now working with .NET 7, WASM builds fine on Linux locally but throws an error when trying to host on Amplify:
![uno_wasm_on_amplify_error_davidconoh](https://user-images.githubusercontent.com/20891707/222680770-f5e2e0f1-7f88-4634-b936-b3b011c4506b.jpg)
With the root directory containing other target folders, this is the content of my `amplify.yml` file:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - cd UnoWasmAWS.Wasm
        - curl -sSL https://dot.net/v1/dotnet-install.sh > dotnet-install.sh
        - chmod +x *.sh
        - ./dotnet-install.sh -c 7.0 -InstallDir ./dotnet7
        - ./dotnet7/dotnet --version
    build:
      commands:
        - ./dotnet7/dotnet publish -c Release -o release
  artifacts:
    baseDirectory: /release/wwwroot
    files:
      - '**/*'
  cache:
    paths: []

```
