### DISCUSSION TITLE
Uno WASM build and Deployment: Azure action build and deploy "Could not detect any platform in the source directory"

### DISCUSSION THREAD

**Discussion by Robotuner** [unoplatform/uno#13513] [Q&A]
I'm sure there is something wrong with my action.  I am getting the following:
```
Try to validate location at: '/github/workspace/FoodTruckNotification/FoodTruckNotification.Wasm/bin/Release/net7.0/dist'.
App Directory Location: 'FoodTruckNotification/FoodTruckNotification.Wasm/bin/Release/net7.0/dist' was found.
Try to validate location at: '/github/workspace/swa-db-connections'.
Looking for event info
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
Oryx will build app with the following custom override command: dotnet build
---Oryx build logs---


Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20230717.2, Commit: 174f4287104c15e6f9ea3a4cf6e9f80accba3cf3, ReleaseTagName: 20230717.2

Build Operation ID: 1074f932d13cc62b
OS Type           : bullseye
Image Type        : jamstack

Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.


---End of Oryx build logs---
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
Finished building app with Oryx`
```

Does anyone have any idea what would cause this?  The Uno app builds and runs locally, I have another Uno wasm project that seems to build fine with basically the same settings.  My action looks like:

name: Azure Static Web Apps CI/CD

```yaml
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with: 
          dotnet-version: '7.0.100'
      - run: |
          cd FoodTruckNotification/FoodTruckNotification.Wasm
          dotnet restore
          dotnet build -c Release    
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_SKY_0DD2BE310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "FoodTruckNotification/FoodTruckNotification.Wasm/bin/Release/net7.0/dist" # App source code path
          ###### api_location: "EmailNotificationAPI" # Api source code path - optional
          output_location: "wwwroot" # Built app content directory - optional
          ###### app_build_command: "dotnet build"
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_SKY_0DD2BE310 }}
          action: "close"
```

**Comment by jeromelaban** [comment]
Thanks for the question. This is likely the result of the `output_location` parameter not being empty.

The original [documentation is located here](https://platform.uno/docs/articles/guides/azure-static-webapps.html#publishing-uno-platform-webassembly-app-on-azure), and we're using [azure static apps in this repository](https://github.com/unoplatform/uno.toolkit.ui/blob/4c78e92d76f8a2eb222c89f2875c0987f6244df2/.github/workflows/azure-static-webapp.yml#L54).

If this is the case, we'll be glad to accept your contribution on making our docs clearer!

**Reply by Robotuner** [reply]
I started with the out_put location left as an empty string.  That didn't work, I tried a bunch of different permutations of the settings hoping that something would shake loose.  Nothing has.  I have updated my action to use the setup-dotnet@v1.7.2 and dotnet-version: '7.0.302'.  Neither change made a difference, I still get the same error.  Is my location correct, do I need to go all the way down to /bin/Release/net7.0/dist?  I could not tell in the example since it is "${{ env.DIST_PATH }}"

**Reply by jeromelaban** [reply]
Thanks. In the example, `DIST_PATH` is defined [here](https://github.com/unoplatform/uno.toolkit.ui/blob/4c78e92d76f8a2eb222c89f2875c0987f6244df2/.github/workflows/azure-static-webapp.yml#L17C7-L17C16). Can you provide the log again without the `output_location` being set?

**Reply by Robotuner** [reply]
Thanks.  I've attached the entire log archive of my recent attempt.
[logs_118.zip](https://github.com/unoplatform/uno/files/12550002/logs_118.zip)
and here is the action

```yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with: 
          dotnet-version: '7.0.302'
      - run: |
          cd FoodTruckNotification/FoodTruckNotification.Wasm
          dotnet build -c Release    
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_SKY_0DD2BE310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "FoodTruckNotification/FoodTruckNotification.Wasm/bin/Release/net7.0/dist" # App source code path
          ###### api_location: "EmailNotificationAPI" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### app_build_command: "dotnet build"
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_SKY_0DD2BE310 }}
          action: "close"
```

Is it possible that something in my wasm code is throwing an uncaught exception in the build leading to could not detect platform message?

Thanks
