### DISCUSSION TITLE
Uno Extensions menu often missing from VS2022

### DISCUSSION THREAD

**Discussion by HakanL** [unoplatform/uno#20545] [Q&A] [answered]
Often it seems that the Uno Extension menu is missing from Visual Studio 2022, is there something I'm missing? I have the toolbar in my app, but if I select Settings then nothing happens.

![image](https://github.com/user-attachments/assets/f4091b4c-971c-4c56-ab6a-7d0fa5dddd46)
![image](https://github.com/user-attachments/assets/810b00e4-257b-4874-9c95-117a669bf79b)

I enabled the MSBuild Diagnostics log, it turned out to be 32 MB 😨 but attached here.
[MsBuild Uno Extension logs.zip](https://github.com/user-attachments/files/20418650/MsBuild.Uno.Extension.logs.zip)

The extension menu is there when I create a new simple Uno project from the templates, so it's definitely something in my more complex solution that is causing it, but I figured it would be good for you to figure it out if it affects other users as well.

**Comment by jeromelaban** [comment]
Thanks for the report.

It seems that some of the projects in the solution are not building properly:
```
D:\Projects\OpenSource\Haukcode-sACN\src\Haukcode.sACN\Haukcode.sACN.csproj : error MSB4057: The target "UnoDumpTargetFrameworks" does not exist in the project.
D:\Projects\OpenSource\Haukcode-KiNet\src\Haukcode.KiNet\Haukcode.KiNet.csproj : error MSB4057: The target "UnoDumpTargetFrameworks" does not exist in the project.
D:\Projects\OpenSource\Haukcode-ArtNet\src\ArtNet\Haukcode.ArtNet.csproj : error MSB4057: The target "UnoDumpTargetFrameworks" does not exist in the project.
```

Are those projects parts not part of a solution filter, or something similar?

**Reply by HakanL** [reply]
Hmm, they are part of the solution and the whole solution builds fine (I can't remember if the build logs I attached were from just opening the solution, or if I was rebuilding, let me know if you want me to try something else).
![image](https://github.com/user-attachments/assets/4ca47053-d0f0-4e0e-b9cf-090727cd62af)

**Reply by dr1rrb** [reply]
@HakanL Looking at your logs, I don't see any project where the target `UnoDumpTargetFrameworks` is completing properly. Either the failure mentioned by Jérôme -which might be ignored in some cases-, either this:

```
[DEBUG][17:02:58.97]       17:01:59.161  10:9>UnoDumpTargetFrameworks: (TargetId:75)
[DEBUG][17:02:58.97]                            This is not a Uno.SDK project, no TFM to dump. (TaskId:57)
```

Are you using the `Uno.Sdk` in at least one of your projects? (I see that at least `AdminSite.csproj` seems to be using it, but just to confirm)

Would be interesting also to know which kind of projects are:
* Haukcode.sACN.csproj
* Haukcode.KiNet.csproj
* Haukcode.ArtNet.csproj

Are they Uno.SDK projects? Application/Library projects?

**Reply by HakanL** [reply]
I have one project (the "main" project, UnoHost) using "Uno.Sdk", the rest of the projects are normal "Microsoft.NET.Sdk". AdminSite is "Microsoft.NET.Sdk.Web".
This is a private/commercial project, but I'm happy to share it with you if you want to use it for troubleshooting the extension, just let me know how I can sent it to you.

**Reply by dr1rrb** [reply]
Ok found the issue, it's because the `UnoDumpTargetFrameworks` is being overridden by the "default" one that is dynamically injected to avoid MSB4057 errors (@ line 309551):

```
Overriding target "UnoDumpTargetFrameworks" in project "D:\_Cache\NuGet\uno.sdk\6.1.0-dev.148\targets\Uno.Build.targets" with target "UnoDumpTargetFrameworks" from project "D:\_Cache\NuGet\uno.winui.devserver\6.1.0-dev.445\tools\rc\host\net9.0\DevServer.Custo
```

Not sure yet what are the rules for this override, but I would suspect that it's just using the most recent version. I was suspecting multiple version being referenced in your solution ... but actually I found that we have conflicting properties when building your `UnoHost.csproj`:

```
@100379: _UnoSdkTargetsDirectory = D:\_Cache\NuGet\uno.sdk\6.1.0-dev.148\targets\
@101258: UnoVersion = 6.1.0-dev.445
```

Not sure yet why ... are you setting explicit version of uno somewhere? (You can search in the whole solution for "6.1.0-dev.148"). Do you have a project that is referencing the `Uno.WinUI` package directly?

Also I noticed that you have an explicit reference to the toolkit in your `UnoHost.csproj` file (@ line 124343):
```
[DEBUG][17:02:34.83]                          D:\_Cache\NuGet\uno.sdk\6.1.0-dev.148\targets\Uno.Implicit.Packages.targets(33,3): message UNOB0009: Uno Platform Implicit Package references are enabled, you should remove these references from your csproj: [D:\Projects\DMXCore\100\Software\UnoHost\UnoHost.csproj]
[DEBUG][17:02:34.83]                          D:\_Cache\NuGet\uno.sdk\6.1.0-dev.148\targets\Uno.Implicit.Packages.targets(33,3): message UNOB0009: 	<PackageReference Include="Uno.Toolkit.WinUI" /> [D:\Projects\DMXCore\100\Software\UnoHost\UnoHost.csproj]
[DEBUG][17:02:34.83]                          D:\_Cache\NuGet\uno.sdk\6.1.0-dev.148\targets\Uno.Implicit.Packages.targets(33,3): message UNOB0009: See https://aka.platform.uno/UNOB0009 for more information. [D:\Projects\DMXCore\100\Software\UnoHost\UnoHost.csproj]
[DEBUG][17:02:34.83]                          D:\_Cache\NuGet\uno.sdk\6.1.0-dev.148\targets\Uno.Implicit.Packages.targets(33,3): message UNOB0009:  [D:\Projects\DMXCore\100\Software\UnoHost\UnoHost.csproj] (TaskId:42)
```

Does your project is on GitHub? If so if you could just give access to me. If not, which platform are your using for you repo?

**Reply by dr1rrb** [reply]
Oh ... one is WinUI package while the other one SDK, so it makes sense to have different version. Need to investigate more ...

**Reply by HakanL** [reply]
I searched for either of those strings, not in my solutions, so not sure where they were coming from.
The solution is a combination of open source projects hosted on Github and two private repos in Bitbucket. I'm happy to give you access to those on Bitbucket. Then to actually build you need to have them in specific folders (just because of how this project came about, haven't consolidated). This is part of the build script, hopefully that will give you enough details of what to check out to get it to build.
```
resources:
  repositories:
    - repository: MagnusEngine
      type: bitbucket
      endpoint: Bitbucket - hakanl
      name: DMXCore/MagnusEngine
      ref: main
    - repository: HaukcodeSACN
      type: github
      endpoint: github.com_HakanL
      name: hakanl/Haukcode.sACN
      ref: main
    - repository: HaukcodeArtNet
      type: github
      endpoint: github.com_HakanL
      name: hakanl/Haukcode.ArtNet
      ref: main
    - repository: HaukcodeKiNet
      type: github
      endpoint: github.com_HakanL
      name: hakanl/Haukcode.KiNet
      ref: main
    - repository: HaukcodeMeadow
      type: github
      endpoint: github.com_HakanL
      name: hakanl/Meadow.DotNetIoT
      ref: main

steps:
- checkout: self
  path: s/DMXCore/100/Software
- checkout: MagnusEngine
  path: s/DMXCore/MagnusEngine
- checkout: HaukcodeSACN
  path: s/OpenSource/Haukcode-sACN
- checkout: HaukcodeArtNet
  path: s/OpenSource/Haukcode-ArtNet
- checkout: HaukcodeKiNet
  path: s/OpenSource/Haukcode-KiNet
- checkout: HaukcodeMeadow
  path: s/OpenSource/Haukcode-Meadow.DotNetIoT
```
