### DISCUSSION TITLE
[WASM] HelloApp-Wasm (.net 6), Azure Static Web App issue

### DISCUSSION THREAD

**Discussion by Grzesik** [unoplatform/uno#9607] [Q&A]
I’m looking for a working example, how to deploy the simplest HellpApp.Wasm **(.net6**) to **Azure Static Web App**. I’ve found only this description [Hosting Uno Platform WebAssembly apps on Azure Static Web Apps](https://platform.uno/docs/articles/guides/azure-static-webapps.html), which works for .net 5 but not for a .net 6 project. 
I’ve changed the github action to:

`jobs:
	  build_and_deploy_job:
	    env:
	        DIST_PATH: UnoApp2/UnoApp2.Wasm/bin/Release/net6.0/dist
	  
	    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
	    runs-on: ubuntu-latest
	    container: 'unoplatform/wasm-build:3.0'
	    name: Build and Deploy Job
	    steps:
	      - uses: actions/checkout@v2
	        with:
	          fetch-depth: 0 # Required for gitversion
	          submodules: true
	          
	      - name: Setup dotnet
	        uses: actions/setup-dotnet@v1.7.2
	        with:
	          dotnet-version: '6.0.200'
	

	      - run: |
	          cd UnoApp2/UnoApp2.Wasm
	          dotnet build -c Release "/p:PackageVersion=${{ steps.gitversion.outputs.fullSemVer }}" /p:DisableNet6MobileTargets=true
	          
	        name: Build And Deploy
	      
	      - uses: actions/upload-artifact@v2
	        with:
	          name: wasm-site
	          path: ${{ env.DIST_PATH }}`

I get a following error:

`/github/home/.nuget/packages/uno.wasm.bootstrap/3.3.1/build/Uno.Wasm.Bootstrap.targets(175,5): error : System.Exception: Failed to execute the linker [/__w/UnoApp2/UnoApp2/UnoApp2/UnoApp2.Wasm/UnoApp2.Wasm.csproj]
/github/home/.nuget/packages/uno.wasm.bootstrap/3.3.1/build/Uno.Wasm.Bootstrap.targets(175,5): error :    at Uno.Wasm.Bootstrap.ShellTask_vfc89b40db92a14b8f04d4c5c9c72690bdcd7b878.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 927 [/__w/UnoApp2/UnoApp2/UnoApp2/UnoApp2.Wasm/UnoApp2.Wasm.csproj]
/github/home/.nuget/packages/uno.wasm.bootstrap/3.3.1/build/Uno.Wasm.Bootstrap.targets(175,5): error :    at Uno.Wasm.Bootstrap.ShellTask_vfc89b40db92a14b8f04d4c5c9c72690bdcd7b878.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 228 [/__w/UnoApp2/UnoApp2/UnoApp2/UnoApp2.Wasm/UnoApp2.Wasm.csproj]
`

**Comment by jeromelaban** [comment]
Can you provide the binlog out of this build? See https://platform.uno/docs/articles/uno-builds-troubleshooting.html for details.

**Reply by jeromelaban** [reply]
(Make sure to answer on this thread)

The logs you provided are not the ones from the link above. Make sure to use the documentation above to add the parameter `/bl` to your command line. The artifact needed here is a `.binlog` file.

**Reply by Grzesik** [reply]
I added /bl parameter in the github action, but so really I can't find the artifacts in azure or in Github. The only log I could find was the one I sent. 
Anyway the thing is, I created just a new Uno-Platform App with Wasm support and .net6 (VS2022 17.3.2). I didn't change anything. It works fine locally. Than I created the Azure Static Web App and changed the Github Action. That's it. Unfortunatelly it doesn't work and there is no sample, how to do it. The samples are with Wasm and .Net5. I tried to copy the Github Action from Uno-Platform Projects in Github, but all the Wasm Projects use .net5. 
Do you have an example of a Github Action, which works for Wasm and .net6?

**Reply by jeromelaban** [reply]
You'll need to publish artifacts to get the binlog file. This project does not have this particular binlog export, but it uses github actions: https://github.com/unoplatform/Uno.Themes/blob/master/.github/workflows/azure-static-webapp.yml

**Reply by Grzesik** [reply]
Yes, I copied my Github Action from there, but the wasm projet uses .NET5!
https://github.com/unoplatform/Uno.Themes/blob/master/src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Wasm/Uno.Themes.Samples.Wasm.csproj

**Reply by jeromelaban** [reply]
Thanks, indeed this project still uses net5. Can you still provide the binlog, there's the technique to get the artifacts there. You can specify the output path using `/bl:myfile.binlog` and point it to the artifacts folder.

**Reply by Grzesik** [reply]
Hi, actually I solved my problem so, that I disabled the linker.

```
<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<WasmShellILLinkerEnabled>false</WasmShellILLinkerEnabled>
</PropertyGroup>

```
in the project file. (  https://platform.uno/docs/articles/features/using-il-linker-webassembly.html )
Unfortunatelly the files are big and it takes more time to start the app.

I'll ask my friend, how to download the artifacts from Github and I'll send you the .binlog tomorrow.

Thanks!

**Reply by Grzesik** [reply]
[binlog.zip](https://github.com/unoplatform/uno/files/9434016/binlog.zip)

**Reply by Grzesik** [reply]
I managed it, to create the binlog. The log includes the linker error, like at the top of the conversation. 
I've changed the Github Action, to use the latest .net6 and to create the log:

```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    env:
        DIST_PATH: UnoApp2/UnoApp2.Wasm/bin/Release/net6.0/dist
  
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: mkdir -p myartifact
          
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - name: Display dotnet version
        run: dotnet --version
      
      - name: Build
        run: |
          cd UnoApp2/UnoApp2.Wasm
          dotnet build -bl:../../myartifact/output.binlog -c Release
          
      - name:  Deploy
        uses: actions/upload-artifact@v3
        with:
          name: wasm-site
          path: ${{ env.DIST_PATH }}
          
      - name:  Deploy 2
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: binlog
          path: myartifact/
      
      - name: Publish to Azure Static WebApps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_TREE_056240103 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location:  "${{ env.DIST_PATH }}" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_TREE_056240103 }}
          action: "close"
```
