### DISCUSSION TITLE
[WASM] Wasm App(.net 6) deploy to Azure Static Web App with Azure Pipelines

### DISCUSSION THREAD

**Discussion by Grzesik** [unoplatform/uno#9966] [Q&A]
Hi, I’m looking for an example, how to deploy a Wasm App to Azure Static Web App with Azure Pipeline. I mean the yml file.  I managed to do this with Github Actions [(see here )](https://github.com/unoplatform/uno/discussions/9607)

Unfortunately Azure Pipele is not with Github Actions compatible. 

I started so:

```
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Setup .Net 6.x'
  inputs:
    version: 6.x

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: '$(solution)'
    feedsToUse: select
```

The last command causes an error:

```
NuGet.CommandLine.ExitCodeException: Exception of type 'NuGet.CommandLine.ExitCodeException' was thrown. 
at NuGet.CommandLine.MsBuildUtility.GetProjectReferencesAsync (NuGet.CommandLine.MsBuildToolset msbuildToolset, System.String[] projectPaths, System.Int32 timeOut, NuGet.CommandLine.IConsole console, System.Boolean recursive, System.String solutionDirectory, System.String solutionName, System.String restoreConfigFile, System.String[] sources, System.String packagesDirectory, NuGet.ProjectModel.RestoreLockProperties restoreLockProperties) [0x00489] in <5e950d42c1b54c53ba3c01c2accdeea8>:0 
at NuGet.CommandLine.RestoreCommand.GetDependencyGraphSpecAsync (System.String[] projectsWithPotentialP2PReferences, System.String solutionDirectory, System.String solutionName, System.String configFile) [0x0012b] in <5e950d42c1b54c53ba3c01c2accdeea8>:0 
at NuGet.CommandLine.RestoreCommand.DetermineInputsFromMSBuildAsync (NuGet.CommandLine.RestoreCommand+PackageRestoreInputs packageRestoreInputs) [0x000e5] in <5e950d42c1b54c53ba3c01c2accdeea8>:0 
/tmp/NuGetScratch/p5iq7quh.5ry.nugetrestore.targets(164,5): error MSB4018: The "WriteRestoreGraphTask" task failed unexpectedly. [/tmp/NuGetScratch/8kxoajbb.4ra.nugetinputs.targets]
```

**Comment by sarosigy** [comment]
It seems the pretty default yml to me.

First, it is enough to restore the wasm .csproj dependencies:

```
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'MyProject.Wasm/MyProject.Wasm.csproj'
    feedsToUse: 'select'

```
and build to somewhere, in this example to staging directory:

```
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'MyProject.Wasm/MyProject.Wasm.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

```

To deploy, it depends on what you have. There are a many number of deployment tasks, you have to pick the one, and choose the source of the deployment the `$(Build.ArtifactStagingDirectory)/dist` where the result of the build is.

**Comment by Grzesik** [comment]
Thanks for your help. My yml looks now so:

```
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  project: 'Museum2goWeb/Museum2goWeb.Wasm/Museum2goWeb.Wasm.csproj'
  applocation: 'Museum2goWeb/Museum2goWeb.Wasm'
  dist_path: Museum2goWeb/Museum2goWeb.Wasm/bin/Release/net6.0/dist
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  token: 'xxx'

steps:

- task: UseDotNet@2
  displayName: 'Setup .Net 6.x'
  inputs:
    packageType: 'sdk'
    version: 6.x

- task: CmdLine@2
  inputs:
    script: 'dotnet --version'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: '$(project)'
    feedsToUse: select
    

- task: CmdLine@2
  inputs:
    script: |
      cd Museum2goWeb/Museum2goWeb.Wasm
      dotnet build -c $(BuildConfiguration)

- task: AzureStaticWebApp@0
  inputs:
    app_location: $(dist_path)
    azure_static_web_apps_api_token: $(token)
```

Unfortunately the last step to upload the artifacts to azure static web app doesn't work.  I use also an another command to build the app like in my Githiub Actions. Your example logged, that it is compiled with an old .Net Core. But the log is not so clear, if it is the case.

Do you have may be an example how to upload the artifacts to Azure static web apps? 
In the Github Actions the build and deploy tasks look so:

```
- name: Build
        run: |
          cd Museum2goWeb/Museum2goWeb.Wasm
          dotnet build -c Release
          
      - name:  Deploy
        uses: actions/upload-artifact@v3
        with:
          name: wasm-site
          path: ${{ env.DIST_PATH }}  
      
        
      - name: Publish to Azure Static WebApps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_BUSH_0C9639A03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "${{ env.DIST_PATH }}" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

```

**Reply by jeromelaban** [reply]
Make sure to provide the error you're getting when saying it does not work, it avoid back and forth to ask you what it is.

On Uno's side, we're generally using the Azure DevOps  "Azure Static Apps" Release task to publish apps, by using the feature that can use an already built app from the associated build pipeline.

**Reply by Grzesik** [reply]
Hi Jerome, sorry for the lack of error info. I was looking for an example, how to use the Azure Pipelines with Azure Static Web App. Your projects use the Azure Pipelines not with Azure Static Web App, therefore I couldn't so really use it as an example. At the edn I found a way how to create this pipeline.

```
# Uno Platform - Wasm (.NET 6)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  project: 'Museum2goWeb/Museum2goWeb.Wasm/Museum2goWeb.Wasm.csproj'
  applocation: 'Museum2goWeb/Museum2goWeb.Wasm'
  dist_path: Museum2goWeb/Museum2goWeb.Wasm/bin/Release/net6.0/dist
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
steps:

- task: UseDotNet@2
  displayName: 'Setup .Net 6.x'
  inputs:
    packageType: 'sdk'
    version: 6.x

- task: CmdLine@2
  inputs:
    script: 'dotnet --version'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: '$(project)'
    feedsToUse: select

- task: CmdLine@2
  inputs:
    script: |
      cd Museum2goWeb/Museum2goWeb.Wasm
      dotnet build -c $(BuildConfiguration) 

- task: AzureStaticWebApp@0
  inputs:
    skip_app_build: true
    skip_api_build: true
    app_location: $(dist_path)
    azure_static_web_apps_api_token: $(museum2goToken)
```

It can be an example for developers, who want to use Azure Pipelines with Azure Static Web App. To use Github Actions with Azure Static Web App, it can be found here: [https://github.com/unoplatform/uno/discussions/9607#discussioncomment-3484449](https://github.com/unoplatform/uno/discussions/9607#discussioncomment-3484449)

I created a simple web page for my  app [https://www.museum2go.com/](https://www.museum2go.com/). It works OK, but takes 7 sec to start the first time. It's because I have to switch off the linker. (Bug [https://github.com/unoplatform/uno/issues/9628](https://github.com/unoplatform/uno/issues/9628)). It is too long for a user. I hope, that with a Linker switched on, I can decrease the time to 3 sec.

Anway the Uno Platform / Wasm is awesome :-) !
Thanks!
