### ISSUE TITLE
Default VS Azure Web App publish YML is not compatible with Uno

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#14796]
### Current behavior

The Publish in VS generates the following YML on the Wasm/Server project

```yml
name: Build and deploy .NET Core application to Web App unexpectedapis
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: unexpectedapis
  AZURE_WEBAPP_PACKAGE_PATH: UnexpectedApis.Server\publish
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: UnexpectedApis.Server
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.unexpectedapis_DBB3 }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

```

This however does not work and the generated zip artifact does not contain the `_package`, etc. folders in `wwwroot`.

Removing `--no-build` from `dotnet publish` fixes the problem

### Expected behavior

Should work by default.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022
