### ISSUE TITLE
Conditionally run CI based upon contents that have changed.

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1486]
## What would you like to be added:

A little bit of smarts to make CI cycle time faster, some ideas:

- If PR is to README.md then don't run CI.
- If PR is to docs/* then don't build src/* (nb. may not be possible - is there a dependency on uwpsyncgenerator?)

## Why is this needed:

This PR https://github.com/unoplatform/uno/pull/1485/files took and hour to build :p

## Anything else we need to know?

Alternatives include fixing the `mergify` autocomplete but it would require some adjustments to our brand protection rules. Opening this as `help wanted`.

**Comment by Xiaoy312** [comment]
We could probably update the `.vsts-ci.yml` with triggers like:
```
trigger:
  branches:
  - master
  - dev/*
  - release/*
  - feature/*
  - projects/*
  paths:
    include:
    - '/'
    exclude:
    - .dependabot/
    - .github/
    - .editorconfig
    - '*.md'
    - .all-contributorsrc

pr:
  branches:
  - master
  - dev/*
  - release/*
  - feature/*
  - projects/*
  paths:
    include:
    - '/'
    exclude:
    - .dependabot/
    - .github/
    - .editorconfig
    - '*.md'
    - .all-contributorsrc
```
ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#triggers

---

Or, alternatively modify the `allcontributors` bot to append these in its commits:
- `[skip ci]` or `[ci skip]`
- `skip-checks: true` or `skip-checks:true`
- `[skip azurepipelines]` or `[azurepipelines skip]`
- `[skip azpipelines]` or `[azpipelines skip]`
- `[skip azp]` or `[azp skip]`
- ` ***NO_CI***`

ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#opting-out-of-ci-builds
