### ISSUE TITLE
Uno.Resizetizer should not be in api doc when a uno app is part of docfx metadata

### ISSUE THREAD

**Issue by DevTKSS** [unoplatform/uno#20550]
### Current behavior

I included an regular Uno app v5.x in a docfx metadata src but beside my own api, it always also published the Uno.Resizetizer as part of my application api which os not the case at all obviously!

### Expected behavior

As every nuget provided api the resizetizer should not get listed as public api of an uno app

### How to reproduce it (as minimally and precisely as possible)

Create metadata api from a uno app by using docfx abd only let it use public api of your app as default set , look in the generated metadata

### Workaround

Add a exclude with Uno.Resizetizer to the docfx.json

### Works on UWP/WinUI

None

### Environment

Other, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Renderer

- [ ] Skia
- [ ] Native

### Affected platforms

Build tasks

### IDE

Visual Studio Code, Visual Studio 2022

### IDE version

17.3.x

### Anything else we need to know?

If you know of any changes on resizetizer to 6.0 version I can try it with that version applyed again...

**Comment by DevTKSS** [comment]
current output produced locally via docfx:

this did include a filter already for `build>content>exclude` "api/Uno.Resizetizer*.yml" :

<img width="560" height="183" alt="Image" src="https://github.com/user-attachments/assets/46a13522-d400-43c9-bcbb-557e396b5134" />

because neither my MvuxGallery, nor myself be the Owner or Publisher of the Uno.Resizetizer or any nested Namespace of it, the Resizetizer generated (?) output to process the assets, seems to be set to public accessor, which then causes the symbols to get published as mine.

Althought the docfx settings are or better said "should" exclude the **/obj/** folder, it seems like this is not considered by the CLI tool, because as I found the Uno.Resizetizer generated output *only* in the obj/Debug/* folder:

<img width="1841" height="682" alt="Image" src="https://github.com/user-attachments/assets/c3a374d6-8ad7-42ee-8dc6-ed17c9997d22" />

(the content of the function seems to be conditionally disabled, is this correct also to be this way for Desktop target?)

I would not know, why the Resizetizer generated code should be public accessor so maybe someone could take a look on this?
Will file this as primary on their side issue on docfx repo, hoping this will get fixed somehow. But the problems with generated files and "duplicated files" seem to be already for years a problem, so I have no real hope this will get solved anytime soon.

**Comment by DevTKSS** [comment]
@jeromelaban is there any specific reason for the generated code (?) of the Resizetizer to have a public accessor and therefore pop up in api doc for a uno ui app like mine?

**Comment by DevTKSS** [comment]
@ajpinedam for an eventually repro or lookup for you to hopefully help on this issue here maybe:
- https://github.com/DevTKSS/DevTKSS.Uno.SampleApps/pull/11

There is the problem causing branch linked and you can see the FilterConfig I am using in the attached files of that PR.
The resizetizer content I got excluded with this from the docfx output, but not the mvux products🤔
A possible workaround until those might could be generated as non public accessor would be, if there would be a FilterConfig available that would exclude them🤔

**Comment by Kunal22shah** [comment]
Generated metadata from compiled net9.0-desktop DLL.
With default filter enabled, there are no `api/Uno.Resizetizer*.yml` files and no references to `“Uno.Resizetizer”` in any generated YAML:

<img width="1237" height="977" alt="Image" src="https://github.com/user-attachments/assets/0e8dee90-6e2c-48d2-8fda-c51b190ad4dd" />

Tested with :

Templates/SDK: `6.3.14`
DocFX 2.78.3
Platform(s): Desktop
IDE: VS 2022 - 17.14.12
OS: Windows

**Comment by DevTKSS** [comment]
@Kunal22shah so as uno projects are c# with csproj I would readed the docfx docs that we would need to define the csproj for reference of DocFx, but you used the dll instead. So just to have that like someone else would do along those docs advices, would you be able to check if thats the same result ehen Using the csproj whith the normal dotnet build DocFx does as reference?
And as I had indeed this very ugly api outcome with mvux + navigation used in my app, I would like to know how we could get rid of those parts of the API of our apps, which are not realistically call-able from an external app, not beeing influenceable enough from ourselves either as they are generated also.
I failed on filtering them our on my DevTKSS.Uno.SamplesApps repo branch that were meant to include api docs but failed on the issued api and that non possibility of not publishing that mvux part of my api including the ReactiveViewModelMappings also.

You could try it out here: https://github.com/DevTKSS/DevTKSS.Uno.SampleApps/pull/11
Thats were I was failing on exactly.🤷
From what I see on your verification comment here, I would still have that problem of horrible ugly api docs that no human could understand and nobody would be realistically able to call that ReactiveViewModelMappings API parts let alone any mvux generated api🤷

**Comment by DevTKSS** [comment]
@Kunal22shah @Jen-Uno  Found the problem that was still causing my api docs to be not filtered correctly and would let you know about the solution, so if someone else might come up with this problem again, you then know what did work last time 👍 

As my Apps do most of the time use Mvux source gen but I would not want those generated files just like the Resizetizer ones to get shown in my api docs.
In the end the reasons my filterConfig for this two generators were not doing as they should:
- `type:` elements in those docfx yml files are case sensitive -> my wrong code: `type: type` or `type: namespace` while those should have been uppercase capital letter: `type: Type` and so on.
- Regex was always dependant on my project and could be simplified -> now its not longer dependant config on just my project, I could copy paste it into any other project
- I had no idea how to sort out the ViewModel's correctly -> docfx does consider Attributes!

my resulting filterConfig.yml:

```yml
# YAML-Language Server: $schema=https://raw.githubusercontent.com/dotnet/docfx/main/schemas/filterconfig.schema.json
apiRules:
  - exclude:
      uidRegex: ^Uno\.Resizetizer$
      type: Namespace
  - exclude:
      uidRegex: ReactiveViewModelMappings$
      type: Type
  - exclude:
      uidRegex: GlobalStaticResources$
      type: Type
  # Exclude all auto-generated ViewModel types (end with ViewModel suffix)
  - exclude:
      uidRegex: ViewModel$
      type: Type
  # Exclude all types with BindableAttribute (catches generated Bindable*ViewModel types)
  - exclude:
      hasAttribute:
        uid: Uno.Extensions.Reactive.BindableAttribute
      type: Type
  # Exclude __Reactive methods
  - exclude:
      uidRegex: __Reactive(\(.*\))?$
      type: Member
```
created a 2 line change PR for the Global Static Resources generator entry, so we should in the future not longer need this element of the filterConfig 👍 
- https://github.com/unoplatform/uno/pull/21679

used the information in the to be solved Issue:
- https://github.com/unoplatform/uno/issues/18616


Maybe it would make sense to have those information about the Reactive and Bindable generated filtering added to the mvux also? 🤔
