### ISSUE TITLE
[WASM] Font preloading support 

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#693]
## I'm submitting a...
- Feature request

## Current behavior
Fonts specified as WebFonts do not get loaded synchronously, making TextBlock based control measure their content incorrectly. Loading fonts using a data-uri is not a workaround.

## Expected behavior
Fonts are loaded and measured properly.

## Possible workaround

This works as a workaround, forcing fonts to load very early in the app's life cycle:
```css
body::after {
    font-family: 'Symbols';
    background: transparent;
    content: "";
    opacity: 0;
    pointer-events: none;
    position: absolute;
}
```

## Environment

```
Nuget Package: 

Package Version(s): 

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```
